# -*- coding: utf-8 -*-
"""Copie de Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bmQeN-CE768Kg1iXeNgVBWMm8QcFyhrK
"""

Iris Dataset (NumPy + Pandas + Matplotlib + Plotly)

# -------------------------
# 1) Import Libraries
# -------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.datasets import load_iris

# -------------------------
# 2) Load Iris Dataset
# -------------------------
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["target"] = iris.target

df.head()

# Shape and info
print("Shape:", df.shape)
df.info()
df.describe()

# Convert to numpy
arr = df.values

# Calculate mean and std
means = np.mean(arr[:, :4], axis=0)
stds = np.std(arr[:, :4], axis=0)

print("Means:", means)
print("STDs:", stds)

filtered = df[df["sepal length (cm)"] > 5.0]
filtered.head()

plt.hist(df["sepal length (cm)"])
plt.xlabel("Sepal Length")
plt.ylabel("Count")
plt.title("Sepal Length Distribution")
plt.show()

plt.scatter(df["sepal length (cm)"], df["sepal width (cm)"], c=df["target"])
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Sepal Length vs Width")
plt.show()

plt.boxplot(df["petal length (cm)"])
plt.title("Petal Length Boxplot")
plt.show()

fig = px.scatter(
    df,
    x="sepal length (cm)",
    y="sepal width (cm)",
    color=df["target"].astype(str),
    title="Interactive Iris Scatter Plot"
)
fig.show()

fig = px.histogram(
    df,
    x="petal length (cm)",
    nbins=20,
    title="Interactive Petal Length Histogram"
)
fig.show()